[package]
name = "supertonic2-openai"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0"

ort = { version = "2.0.0-rc.11" }

ndarray = { version = "0.17", features = ["rayon"] }
rand = "0.10"
rand_distr = "0.6"

rayon = "1.10"

hound = "3.5"
rustfft = "6.2"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

clap = { version = "4.5", features = ["derive"] }

anyhow = "1.0"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
  "env-filter",
  "fmt",
  "json",
] }

unicode-normalization = "0.1"

regex = "1.10"
tokio = { version = "1.0", features = ["full"] }

tempfile = "3"

axum = { version = "0.8", features = ["macros"] }

opus = { version = "0.3" }
ogg = { version = "0.9" }


[features]
cuda = ["ort/cuda"]
