FROM nvidia/cuda:12.9.0-cudnn-devel-ubuntu24.04 AS builder

RUN apt-get update && apt-get install -y build-essential \
                                         libssl-dev \
                                         pkg-config curl \
                                         libopus-dev \
                                         python3 \
                                         python3-pip \
                                         python3-venv \
                                         curl

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y


WORKDIR /app

# Download ONNX stuff on Hugginface
RUN curl -LsSf https://hf.co/cli/install.sh | bash

RUN /root/.local/bin/hf download Supertone/supertonic-3 --local-dir ./assets

# Copy sources and build
COPY . . 
RUN /root/.cargo/bin/cargo build --release --features cuda

FROM  nvidia/cuda:12.9.0-cudnn-devel-ubuntu24.04 AS runner

RUN apt-get update && apt-get install -y libopus0

WORKDIR /app

# The actual app
COPY --from=builder /app/target/release/supertonic-openai /app/supertonic-openai

# ONNX Runtime shared libraries
COPY --from=builder /app/target/release/libonnxruntime_providers_shared.so /app/libonnxruntime_providers_shared.so
COPY --from=builder /app/target/release/libonnxruntime_providers_cuda.so /app/libonnxruntime_providers_cuda.so
COPY --from=builder /app/target/release/libonnxruntime_providers_tensorrt.so /app/libonnxruntime_providers_tensorrt.so
ENV LD_LIBRARY_PATH=/app:$LD_LIBRARY_PATH

# ONNX models and configs
COPY --from=builder /app/assets /app/assets



ENTRYPOINT ["/app/supertonic-openai", "--gpu"]

